################################################################################
# Automatically-generated file. Do not edit!
# Toolchain: GNU Tools for STM32 (9-2020-q2-update)
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
../lib/bsp/NFC03A1/lib_nfc/lib_NDEF/lib_95HF_wrapper.c \
../lib/bsp/NFC03A1/lib_nfc/lib_NDEF/lib_NDEF.c \
../lib/bsp/NFC03A1/lib_nfc/lib_NDEF/lib_NDEF_AAR.c \
../lib/bsp/NFC03A1/lib_nfc/lib_NDEF/lib_NDEF_Email.c \
../lib/bsp/NFC03A1/lib_nfc/lib_NDEF/lib_NDEF_Geo.c \
../lib/bsp/NFC03A1/lib_nfc/lib_NDEF/lib_NDEF_MyApp.c \
../lib/bsp/NFC03A1/lib_nfc/lib_NDEF/lib_NDEF_SMS.c \
../lib/bsp/NFC03A1/lib_nfc/lib_NDEF/lib_NDEF_Text.c \
../lib/bsp/NFC03A1/lib_nfc/lib_NDEF/lib_NDEF_URI.c \
../lib/bsp/NFC03A1/lib_nfc/lib_NDEF/lib_NDEF_Vcard.c 

OBJS += \
./lib/bsp/NFC03A1/lib_nfc/lib_NDEF/lib_95HF_wrapper.o \
./lib/bsp/NFC03A1/lib_nfc/lib_NDEF/lib_NDEF.o \
./lib/bsp/NFC03A1/lib_nfc/lib_NDEF/lib_NDEF_AAR.o \
./lib/bsp/NFC03A1/lib_nfc/lib_NDEF/lib_NDEF_Email.o \
./lib/bsp/NFC03A1/lib_nfc/lib_NDEF/lib_NDEF_Geo.o \
./lib/bsp/NFC03A1/lib_nfc/lib_NDEF/lib_NDEF_MyApp.o \
./lib/bsp/NFC03A1/lib_nfc/lib_NDEF/lib_NDEF_SMS.o \
./lib/bsp/NFC03A1/lib_nfc/lib_NDEF/lib_NDEF_Text.o \
./lib/bsp/NFC03A1/lib_nfc/lib_NDEF/lib_NDEF_URI.o \
./lib/bsp/NFC03A1/lib_nfc/lib_NDEF/lib_NDEF_Vcard.o 

C_DEPS += \
./lib/bsp/NFC03A1/lib_nfc/lib_NDEF/lib_95HF_wrapper.d \
./lib/bsp/NFC03A1/lib_nfc/lib_NDEF/lib_NDEF.d \
./lib/bsp/NFC03A1/lib_nfc/lib_NDEF/lib_NDEF_AAR.d \
./lib/bsp/NFC03A1/lib_nfc/lib_NDEF/lib_NDEF_Email.d \
./lib/bsp/NFC03A1/lib_nfc/lib_NDEF/lib_NDEF_Geo.d \
./lib/bsp/NFC03A1/lib_nfc/lib_NDEF/lib_NDEF_MyApp.d \
./lib/bsp/NFC03A1/lib_nfc/lib_NDEF/lib_NDEF_SMS.d \
./lib/bsp/NFC03A1/lib_nfc/lib_NDEF/lib_NDEF_Text.d \
./lib/bsp/NFC03A1/lib_nfc/lib_NDEF/lib_NDEF_URI.d \
./lib/bsp/NFC03A1/lib_nfc/lib_NDEF/lib_NDEF_Vcard.d 


# Each subdirectory must supply rules for building sources it contributes
lib/bsp/NFC03A1/lib_nfc/lib_NDEF/lib_95HF_wrapper.o: ../lib/bsp/NFC03A1/lib_nfc/lib_NDEF/lib_95HF_wrapper.c lib/bsp/NFC03A1/lib_nfc/lib_NDEF/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m3 -std=gnu11 -g3 -DSTM32F1 -DNUCLEO_F103RB -DSTM32F103RBTx -DSTM32 -DDEBUG -DUSE_HAL_DRIVER -DSTM32F103xB -c -I../lib/bsp -I../lib//middleware/MIDI/ -I../lib/bsp/VL53L0X -I../lib/bsp/MPU6050 -I../lib/bsp/iks01a1 -I../lib/bsp/iks01a1/Common -I../lib/bsp/iks01a1/hts221 -I../lib/bsp/iks01a1/lis3mdl -I../lib/bsp/iks01a1/lps22hb -I../lib/bsp/iks01a1/lps25hb -I../lib/bsp/iks01a1/lsm6ds0 -I../lib/bsp/iks01a1/lsm6ds3 -I../lib/bsp/tft_ili9341 -I../lib/bsp/tft_pcd8544 -I../lib/bsp/MCP23S17 -I../lib/hal/inc -I../lib/bsp/Common -I../lib/bsp/lcd2x16 -I../lib/bsp/MLX90614 -I../lib/bsp/MatrixKeyboard -I../lib/bsp/MatrixLed -I../lib/CMSIS/core -I../lib/CMSIS/device -I../lib/middleware/FatFs -I../lib/middleware/FatFs/src -I../lib/middleware/FatFs/src/drivers -I../appli -O0 -ffunction-sections -fdata-sections -Wall -Wextra -Wconversion -fstack-usage -MMD -MP -MF"lib/bsp/NFC03A1/lib_nfc/lib_NDEF/lib_95HF_wrapper.d" -MT"$@"  -mfloat-abi=soft -mthumb -o "$@"
lib/bsp/NFC03A1/lib_nfc/lib_NDEF/lib_NDEF.o: ../lib/bsp/NFC03A1/lib_nfc/lib_NDEF/lib_NDEF.c lib/bsp/NFC03A1/lib_nfc/lib_NDEF/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m3 -std=gnu11 -g3 -DSTM32F1 -DNUCLEO_F103RB -DSTM32F103RBTx -DSTM32 -DDEBUG -DUSE_HAL_DRIVER -DSTM32F103xB -c -I../lib/bsp -I../lib//middleware/MIDI/ -I../lib/bsp/VL53L0X -I../lib/bsp/MPU6050 -I../lib/bsp/iks01a1 -I../lib/bsp/iks01a1/Common -I../lib/bsp/iks01a1/hts221 -I../lib/bsp/iks01a1/lis3mdl -I../lib/bsp/iks01a1/lps22hb -I../lib/bsp/iks01a1/lps25hb -I../lib/bsp/iks01a1/lsm6ds0 -I../lib/bsp/iks01a1/lsm6ds3 -I../lib/bsp/tft_ili9341 -I../lib/bsp/tft_pcd8544 -I../lib/bsp/MCP23S17 -I../lib/hal/inc -I../lib/bsp/Common -I../lib/bsp/lcd2x16 -I../lib/bsp/MLX90614 -I../lib/bsp/MatrixKeyboard -I../lib/bsp/MatrixLed -I../lib/CMSIS/core -I../lib/CMSIS/device -I../lib/middleware/FatFs -I../lib/middleware/FatFs/src -I../lib/middleware/FatFs/src/drivers -I../appli -O0 -ffunction-sections -fdata-sections -Wall -Wextra -Wconversion -fstack-usage -MMD -MP -MF"lib/bsp/NFC03A1/lib_nfc/lib_NDEF/lib_NDEF.d" -MT"$@"  -mfloat-abi=soft -mthumb -o "$@"
lib/bsp/NFC03A1/lib_nfc/lib_NDEF/lib_NDEF_AAR.o: ../lib/bsp/NFC03A1/lib_nfc/lib_NDEF/lib_NDEF_AAR.c lib/bsp/NFC03A1/lib_nfc/lib_NDEF/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m3 -std=gnu11 -g3 -DSTM32F1 -DNUCLEO_F103RB -DSTM32F103RBTx -DSTM32 -DDEBUG -DUSE_HAL_DRIVER -DSTM32F103xB -c -I../lib/bsp -I../lib//middleware/MIDI/ -I../lib/bsp/VL53L0X -I../lib/bsp/MPU6050 -I../lib/bsp/iks01a1 -I../lib/bsp/iks01a1/Common -I../lib/bsp/iks01a1/hts221 -I../lib/bsp/iks01a1/lis3mdl -I../lib/bsp/iks01a1/lps22hb -I../lib/bsp/iks01a1/lps25hb -I../lib/bsp/iks01a1/lsm6ds0 -I../lib/bsp/iks01a1/lsm6ds3 -I../lib/bsp/tft_ili9341 -I../lib/bsp/tft_pcd8544 -I../lib/bsp/MCP23S17 -I../lib/hal/inc -I../lib/bsp/Common -I../lib/bsp/lcd2x16 -I../lib/bsp/MLX90614 -I../lib/bsp/MatrixKeyboard -I../lib/bsp/MatrixLed -I../lib/CMSIS/core -I../lib/CMSIS/device -I../lib/middleware/FatFs -I../lib/middleware/FatFs/src -I../lib/middleware/FatFs/src/drivers -I../appli -O0 -ffunction-sections -fdata-sections -Wall -Wextra -Wconversion -fstack-usage -MMD -MP -MF"lib/bsp/NFC03A1/lib_nfc/lib_NDEF/lib_NDEF_AAR.d" -MT"$@"  -mfloat-abi=soft -mthumb -o "$@"
lib/bsp/NFC03A1/lib_nfc/lib_NDEF/lib_NDEF_Email.o: ../lib/bsp/NFC03A1/lib_nfc/lib_NDEF/lib_NDEF_Email.c lib/bsp/NFC03A1/lib_nfc/lib_NDEF/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m3 -std=gnu11 -g3 -DSTM32F1 -DNUCLEO_F103RB -DSTM32F103RBTx -DSTM32 -DDEBUG -DUSE_HAL_DRIVER -DSTM32F103xB -c -I../lib/bsp -I../lib//middleware/MIDI/ -I../lib/bsp/VL53L0X -I../lib/bsp/MPU6050 -I../lib/bsp/iks01a1 -I../lib/bsp/iks01a1/Common -I../lib/bsp/iks01a1/hts221 -I../lib/bsp/iks01a1/lis3mdl -I../lib/bsp/iks01a1/lps22hb -I../lib/bsp/iks01a1/lps25hb -I../lib/bsp/iks01a1/lsm6ds0 -I../lib/bsp/iks01a1/lsm6ds3 -I../lib/bsp/tft_ili9341 -I../lib/bsp/tft_pcd8544 -I../lib/bsp/MCP23S17 -I../lib/hal/inc -I../lib/bsp/Common -I../lib/bsp/lcd2x16 -I../lib/bsp/MLX90614 -I../lib/bsp/MatrixKeyboard -I../lib/bsp/MatrixLed -I../lib/CMSIS/core -I../lib/CMSIS/device -I../lib/middleware/FatFs -I../lib/middleware/FatFs/src -I../lib/middleware/FatFs/src/drivers -I../appli -O0 -ffunction-sections -fdata-sections -Wall -Wextra -Wconversion -fstack-usage -MMD -MP -MF"lib/bsp/NFC03A1/lib_nfc/lib_NDEF/lib_NDEF_Email.d" -MT"$@"  -mfloat-abi=soft -mthumb -o "$@"
lib/bsp/NFC03A1/lib_nfc/lib_NDEF/lib_NDEF_Geo.o: ../lib/bsp/NFC03A1/lib_nfc/lib_NDEF/lib_NDEF_Geo.c lib/bsp/NFC03A1/lib_nfc/lib_NDEF/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m3 -std=gnu11 -g3 -DSTM32F1 -DNUCLEO_F103RB -DSTM32F103RBTx -DSTM32 -DDEBUG -DUSE_HAL_DRIVER -DSTM32F103xB -c -I../lib/bsp -I../lib//middleware/MIDI/ -I../lib/bsp/VL53L0X -I../lib/bsp/MPU6050 -I../lib/bsp/iks01a1 -I../lib/bsp/iks01a1/Common -I../lib/bsp/iks01a1/hts221 -I../lib/bsp/iks01a1/lis3mdl -I../lib/bsp/iks01a1/lps22hb -I../lib/bsp/iks01a1/lps25hb -I../lib/bsp/iks01a1/lsm6ds0 -I../lib/bsp/iks01a1/lsm6ds3 -I../lib/bsp/tft_ili9341 -I../lib/bsp/tft_pcd8544 -I../lib/bsp/MCP23S17 -I../lib/hal/inc -I../lib/bsp/Common -I../lib/bsp/lcd2x16 -I../lib/bsp/MLX90614 -I../lib/bsp/MatrixKeyboard -I../lib/bsp/MatrixLed -I../lib/CMSIS/core -I../lib/CMSIS/device -I../lib/middleware/FatFs -I../lib/middleware/FatFs/src -I../lib/middleware/FatFs/src/drivers -I../appli -O0 -ffunction-sections -fdata-sections -Wall -Wextra -Wconversion -fstack-usage -MMD -MP -MF"lib/bsp/NFC03A1/lib_nfc/lib_NDEF/lib_NDEF_Geo.d" -MT"$@"  -mfloat-abi=soft -mthumb -o "$@"
lib/bsp/NFC03A1/lib_nfc/lib_NDEF/lib_NDEF_MyApp.o: ../lib/bsp/NFC03A1/lib_nfc/lib_NDEF/lib_NDEF_MyApp.c lib/bsp/NFC03A1/lib_nfc/lib_NDEF/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m3 -std=gnu11 -g3 -DSTM32F1 -DNUCLEO_F103RB -DSTM32F103RBTx -DSTM32 -DDEBUG -DUSE_HAL_DRIVER -DSTM32F103xB -c -I../lib/bsp -I../lib//middleware/MIDI/ -I../lib/bsp/VL53L0X -I../lib/bsp/MPU6050 -I../lib/bsp/iks01a1 -I../lib/bsp/iks01a1/Common -I../lib/bsp/iks01a1/hts221 -I../lib/bsp/iks01a1/lis3mdl -I../lib/bsp/iks01a1/lps22hb -I../lib/bsp/iks01a1/lps25hb -I../lib/bsp/iks01a1/lsm6ds0 -I../lib/bsp/iks01a1/lsm6ds3 -I../lib/bsp/tft_ili9341 -I../lib/bsp/tft_pcd8544 -I../lib/bsp/MCP23S17 -I../lib/hal/inc -I../lib/bsp/Common -I../lib/bsp/lcd2x16 -I../lib/bsp/MLX90614 -I../lib/bsp/MatrixKeyboard -I../lib/bsp/MatrixLed -I../lib/CMSIS/core -I../lib/CMSIS/device -I../lib/middleware/FatFs -I../lib/middleware/FatFs/src -I../lib/middleware/FatFs/src/drivers -I../appli -O0 -ffunction-sections -fdata-sections -Wall -Wextra -Wconversion -fstack-usage -MMD -MP -MF"lib/bsp/NFC03A1/lib_nfc/lib_NDEF/lib_NDEF_MyApp.d" -MT"$@"  -mfloat-abi=soft -mthumb -o "$@"
lib/bsp/NFC03A1/lib_nfc/lib_NDEF/lib_NDEF_SMS.o: ../lib/bsp/NFC03A1/lib_nfc/lib_NDEF/lib_NDEF_SMS.c lib/bsp/NFC03A1/lib_nfc/lib_NDEF/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m3 -std=gnu11 -g3 -DSTM32F1 -DNUCLEO_F103RB -DSTM32F103RBTx -DSTM32 -DDEBUG -DUSE_HAL_DRIVER -DSTM32F103xB -c -I../lib/bsp -I../lib//middleware/MIDI/ -I../lib/bsp/VL53L0X -I../lib/bsp/MPU6050 -I../lib/bsp/iks01a1 -I../lib/bsp/iks01a1/Common -I../lib/bsp/iks01a1/hts221 -I../lib/bsp/iks01a1/lis3mdl -I../lib/bsp/iks01a1/lps22hb -I../lib/bsp/iks01a1/lps25hb -I../lib/bsp/iks01a1/lsm6ds0 -I../lib/bsp/iks01a1/lsm6ds3 -I../lib/bsp/tft_ili9341 -I../lib/bsp/tft_pcd8544 -I../lib/bsp/MCP23S17 -I../lib/hal/inc -I../lib/bsp/Common -I../lib/bsp/lcd2x16 -I../lib/bsp/MLX90614 -I../lib/bsp/MatrixKeyboard -I../lib/bsp/MatrixLed -I../lib/CMSIS/core -I../lib/CMSIS/device -I../lib/middleware/FatFs -I../lib/middleware/FatFs/src -I../lib/middleware/FatFs/src/drivers -I../appli -O0 -ffunction-sections -fdata-sections -Wall -Wextra -Wconversion -fstack-usage -MMD -MP -MF"lib/bsp/NFC03A1/lib_nfc/lib_NDEF/lib_NDEF_SMS.d" -MT"$@"  -mfloat-abi=soft -mthumb -o "$@"
lib/bsp/NFC03A1/lib_nfc/lib_NDEF/lib_NDEF_Text.o: ../lib/bsp/NFC03A1/lib_nfc/lib_NDEF/lib_NDEF_Text.c lib/bsp/NFC03A1/lib_nfc/lib_NDEF/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m3 -std=gnu11 -g3 -DSTM32F1 -DNUCLEO_F103RB -DSTM32F103RBTx -DSTM32 -DDEBUG -DUSE_HAL_DRIVER -DSTM32F103xB -c -I../lib/bsp -I../lib//middleware/MIDI/ -I../lib/bsp/VL53L0X -I../lib/bsp/MPU6050 -I../lib/bsp/iks01a1 -I../lib/bsp/iks01a1/Common -I../lib/bsp/iks01a1/hts221 -I../lib/bsp/iks01a1/lis3mdl -I../lib/bsp/iks01a1/lps22hb -I../lib/bsp/iks01a1/lps25hb -I../lib/bsp/iks01a1/lsm6ds0 -I../lib/bsp/iks01a1/lsm6ds3 -I../lib/bsp/tft_ili9341 -I../lib/bsp/tft_pcd8544 -I../lib/bsp/MCP23S17 -I../lib/hal/inc -I../lib/bsp/Common -I../lib/bsp/lcd2x16 -I../lib/bsp/MLX90614 -I../lib/bsp/MatrixKeyboard -I../lib/bsp/MatrixLed -I../lib/CMSIS/core -I../lib/CMSIS/device -I../lib/middleware/FatFs -I../lib/middleware/FatFs/src -I../lib/middleware/FatFs/src/drivers -I../appli -O0 -ffunction-sections -fdata-sections -Wall -Wextra -Wconversion -fstack-usage -MMD -MP -MF"lib/bsp/NFC03A1/lib_nfc/lib_NDEF/lib_NDEF_Text.d" -MT"$@"  -mfloat-abi=soft -mthumb -o "$@"
lib/bsp/NFC03A1/lib_nfc/lib_NDEF/lib_NDEF_URI.o: ../lib/bsp/NFC03A1/lib_nfc/lib_NDEF/lib_NDEF_URI.c lib/bsp/NFC03A1/lib_nfc/lib_NDEF/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m3 -std=gnu11 -g3 -DSTM32F1 -DNUCLEO_F103RB -DSTM32F103RBTx -DSTM32 -DDEBUG -DUSE_HAL_DRIVER -DSTM32F103xB -c -I../lib/bsp -I../lib//middleware/MIDI/ -I../lib/bsp/VL53L0X -I../lib/bsp/MPU6050 -I../lib/bsp/iks01a1 -I../lib/bsp/iks01a1/Common -I../lib/bsp/iks01a1/hts221 -I../lib/bsp/iks01a1/lis3mdl -I../lib/bsp/iks01a1/lps22hb -I../lib/bsp/iks01a1/lps25hb -I../lib/bsp/iks01a1/lsm6ds0 -I../lib/bsp/iks01a1/lsm6ds3 -I../lib/bsp/tft_ili9341 -I../lib/bsp/tft_pcd8544 -I../lib/bsp/MCP23S17 -I../lib/hal/inc -I../lib/bsp/Common -I../lib/bsp/lcd2x16 -I../lib/bsp/MLX90614 -I../lib/bsp/MatrixKeyboard -I../lib/bsp/MatrixLed -I../lib/CMSIS/core -I../lib/CMSIS/device -I../lib/middleware/FatFs -I../lib/middleware/FatFs/src -I../lib/middleware/FatFs/src/drivers -I../appli -O0 -ffunction-sections -fdata-sections -Wall -Wextra -Wconversion -fstack-usage -MMD -MP -MF"lib/bsp/NFC03A1/lib_nfc/lib_NDEF/lib_NDEF_URI.d" -MT"$@"  -mfloat-abi=soft -mthumb -o "$@"
lib/bsp/NFC03A1/lib_nfc/lib_NDEF/lib_NDEF_Vcard.o: ../lib/bsp/NFC03A1/lib_nfc/lib_NDEF/lib_NDEF_Vcard.c lib/bsp/NFC03A1/lib_nfc/lib_NDEF/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m3 -std=gnu11 -g3 -DSTM32F1 -DNUCLEO_F103RB -DSTM32F103RBTx -DSTM32 -DDEBUG -DUSE_HAL_DRIVER -DSTM32F103xB -c -I../lib/bsp -I../lib//middleware/MIDI/ -I../lib/bsp/VL53L0X -I../lib/bsp/MPU6050 -I../lib/bsp/iks01a1 -I../lib/bsp/iks01a1/Common -I../lib/bsp/iks01a1/hts221 -I../lib/bsp/iks01a1/lis3mdl -I../lib/bsp/iks01a1/lps22hb -I../lib/bsp/iks01a1/lps25hb -I../lib/bsp/iks01a1/lsm6ds0 -I../lib/bsp/iks01a1/lsm6ds3 -I../lib/bsp/tft_ili9341 -I../lib/bsp/tft_pcd8544 -I../lib/bsp/MCP23S17 -I../lib/hal/inc -I../lib/bsp/Common -I../lib/bsp/lcd2x16 -I../lib/bsp/MLX90614 -I../lib/bsp/MatrixKeyboard -I../lib/bsp/MatrixLed -I../lib/CMSIS/core -I../lib/CMSIS/device -I../lib/middleware/FatFs -I../lib/middleware/FatFs/src -I../lib/middleware/FatFs/src/drivers -I../appli -O0 -ffunction-sections -fdata-sections -Wall -Wextra -Wconversion -fstack-usage -MMD -MP -MF"lib/bsp/NFC03A1/lib_nfc/lib_NDEF/lib_NDEF_Vcard.d" -MT"$@"  -mfloat-abi=soft -mthumb -o "$@"

